### ISSUE TITLE
I think we have an issue!

### ISSUE THREAD

**Issue by MakeItBack** [shabaz123/konstruktweb#1]
[Issues](https://guides.github.com/features/issues/) are where people can report bugs or make suggestions for improvements to the code/app.
It's a place where we can discuss ideas and different issues can be tagged to classify them

I can mention people like this @shabaz123 @navbisla

I can use markdown to format things in most places in GitHub, including here - like adding a code block:
```
<h1>Hello Konstruktr team!</h1.
```
Or a line break

---
Or [a link to the project website](http://konstruktr.co.uk/)

**Comment by shabaz123** [comment]
That's very neat. Hope GitHub mobile app sends alerts for these types of comments @MakeItBack and @navbisla
