### ISSUE TITLE
Unable to create branch off main

### ISSUE THREAD

**Issue by navbisla** [shabaz123/konstruktweb#4]
## Cannot switch to new navbranch created on Github website##

Shabaz added nav to collabrators and can create new branches

Have created new branch off master called navbranch and added a dummy txt file navtest.txt. Cannot view or switch to branch on my local. Think its easier to create a new branch on the local and then push it, but I've spent 30 minutes on this and want to figure it out.

*##  **Unable to create branch off main**

- Stackexchange suggests its a security problem and then I need to be a "collabrator" on the project.

https://stackoverflow.com/questions/30948978/cannot-create-branch-in-github*

**Comment by shabaz123** [comment]
Done! You should have a collaborator invite
