### ISSUE TITLE
Home page on local does not seem to pick up Bootstrap css

### ISSUE THREAD

**Issue by navbisla** [shabaz123/konstruktweb#5]
Managed to get the website on my local to display correctly if I substitute in the following **bootstrap.min.css** taken from the bootstrap website

  **<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">**

- Wonder how it displays for Mickey

**Comment by shabaz123** [comment]
Ohh interesting.. you didn't have any CORS issue? I got that error when I tried.
